In [1]:
import numpy as np
import pandas as pd
from sklearn import model_selection
from sklearn.metrics import accuracy_score
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn import tree
import os
from pathlib import Path
from matplotlib import pyplot as plt

In [2]:
data_folder = Path("../data/regression_windfarm/")

inputs = np.load(data_folder / "inputs.npy")
labels = np.load(data_folder / "labels.npy")
X_train, X_test, y_train, y_test = model_selection.train_test_split(inputs, labels, test_size=0.30, random_state=42)

## Linear regression

In [3]:
regr = LinearRegression().fit(X_train, y_train)


In [4]:
scores = model_selection.cross_val_score(regr, X_train, y_train, cv=5)
print(scores)

[ 0.35220839  0.10752322  0.40924719 -0.0946135   0.5827605 ]


In [5]:
prediction = regr.predict(X_test)
print(r2_score(y_test, prediction))

0.7257397173629533


## Support vector regression

In [6]:
regr = make_pipeline(StandardScaler(), SVR(C=1.0, epsilon=0.2)).fit(X_train, y_train)

/home/tristan/anaconda3/envs/ml/lib/python3.8/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [7]:
scores = model_selection.cross_val_score(regr, X_train, y_train, cv=5)
print(scores)

[0.28623523 0.25356053 0.3292629  0.2797167  0.33332115]


/home/tristan/anaconda3/envs/ml/lib/python3.8/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/tristan/anaconda3/envs/ml/lib/python3.8/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/tristan/anaconda3/envs/ml/lib/python3.8/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/tristan/anaconda3/envs/ml/lib/python3.8/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d

In [8]:
prediction = regr.predict(X_test)
print(r2_score(y_test, prediction))

0.3187831773417553


## Random forest

In [9]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression

In [26]:
regr = RandomForestRegressor(max_depth=5).fit(X_train, y_train)

/tmp/ipykernel_21883/3165269696.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  regr = RandomForestRegressor(max_depth=5).fit(X_train, y_train)


In [27]:
scores = model_selection.cross_val_score(regr, X_train, y_train, cv=5)
print(scores)

/home/tristan/anaconda3/envs/ml/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/home/tristan/anaconda3/envs/ml/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/home/tristan/anaconda3/envs/ml/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/home/tristan/anaconda3/envs/ml/lib/python3.8/site-packages/sklearn/model_selec

[0.51730024 0.43111505 0.46876381 0.51997305 0.32761407]


/home/tristan/anaconda3/envs/ml/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


In [28]:
prediction = regr.predict(X_test)
print(r2_score(y_test, prediction))

0.4954020993593301


## Lasso regression

In [13]:
from sklearn import linear_model

In [14]:
lassoReg = linear_model.Lasso(alpha=0.1).fit(X_train,y_train)

In [15]:
scores = model_selection.cross_val_score(regr, X_train, y_train, cv=5)
print(scores)

/home/tristan/anaconda3/envs/ml/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/home/tristan/anaconda3/envs/ml/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/home/tristan/anaconda3/envs/ml/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/home/tristan/anaconda3/envs/ml/lib/python3.8/site-packages/sklearn/model_selec

[0.44339495 0.36359841 0.44906463 0.51669395 0.35122284]


/home/tristan/anaconda3/envs/ml/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


In [16]:
prediction = regr.predict(X_test)
print(r2_score(y_test, prediction))

0.4641085313955733
